# Form implementation generated from reading ui file 'Scouting_UI.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 224)
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setToolTipDuration(-7)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_1.setGeometry(QtCore.QRect(150, 150, 121, 24))
        self.Button_1.setObjectName("Button_1")
        self.Button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_2.setGeometry(QtCore.QRect(350, 150, 131, 24))
        self.Button_2.setObjectName("Button_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 10, 101, 16))
        self.label_7.setObjectName("label_7")
        self.Textbox_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.Textbox_1.setGeometry(QtCore.QRect(30, 40, 611, 61))
        self.Textbox_1.setObjectName("Textbox_1")
        self.Message = QtWidgets.QLabel(self.centralwidget)
        self.Message.setGeometry(QtCore.QRect(30, 120, 501, 20))
        self.Message.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.Message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Message.setObjectName("Message")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 120, 91, 16))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.scan_count = QtWidgets.QLabel(self.centralwidget)
        self.scan_count.setGeometry(QtCore.QRect(560, 140, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setKerning(True)
        self.scan_count.setFont(font)
        self.scan_count.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scan_count.setObjectName("scan_count")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 655, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionTeam_List = QtGui.QAction(MainWindow)
        self.actionTeam_List.setObjectName("actionTeam_List")
        self.menuSettings.addAction(self.actionTeam_List)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_1.setText(_translate("MainWindow", "Clear Input"))
        self.Button_2.setText(_translate("MainWindow", "Output data to excel"))
        self.label_7.setText(_translate("MainWindow", "QR Code to Excel"))
        self.Textbox_1.setPlaceholderText(_translate("MainWindow", "Input QR code here"))
        self.Message.setText(_translate("MainWindow", "Status: Enter First QR Code"))
        self.label.setText(_translate("MainWindow", "Scanned Codes"))
        self.scan_count.setText(_translate("MainWindow", "0"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionTeam_List.setText(_translate("MainWindow", "Team List"))
